/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MPCController */

#ifndef _Included_MPCController
#define _Included_MPCController
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MPCController
 * Method:    controlSignalCVXGEN
 * Signature: ([D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_MPCController_controlSignalCVXGEN
  (JNIEnv *, jobject, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
