/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CVXGENController */

#ifndef _Included_CVXGENController
#define _Included_CVXGENController
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     CVXGENController
 * Method:    controlSignalCVXGEN
 * Signature: ([D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_CVXGENController_controlSignalCVXGEN
  (JNIEnv *, jobject, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
