/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class QPGENController */

#ifndef _Included_QPGENController
#define _Included_QPGENController
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     QPGENController
 * Method:    controlSignalQPGEN
 * Signature: ([D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_QPGENController_controlSignalQPGEN
  (JNIEnv *, jobject, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
